
import { getTopAnime } from './src/services/api.js';
import fs from 'fs';

const FOUND_TITLES = [
    "Wan Sheng Jie",
    "Akagami no Shirayuki-hime 2nd Season",
    "Wolf's Rain OVA",
    "xxxHOLiC",
    "Durarara!!x2 Ten",
    "ReLIFE",
    "Gake no Ue no Ponyo",
    "Kakushigoto",
    "IDOLiSH7 Vibrato",
    "Koukaku Kidoutai 2.0",
    "Hokuto no Ken",
    "Kurenai no Buta",
    "Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou-hen",
    "Fanren Xiu Xian Chuan 2nd Season",
    "Natsu e no Tunnel, Sayonara no Deguchi",
    "Rising Impact Season 2",
    "Benghuai: Xing Qiong Tiedao - Gelamo de Yujin",
    "Cheng He Titong",
    "Ookiku Furikabutte: Natsu no Taikai-hen",
    "Hyouge Mono",
    "Mahou Shoujo Lyrical Nanoha A's",
    "Girls & Panzer: Saishuushou Part 1",
    "Yi Nian Yong Heng",
    "Macross F Movie 2: Sayonara no Tsubasa",
    "Wotaku ni Koi wa Muzukashii OVA",
    "Kobato.",
    "Major Movie: Yuujou no Winning Shot",
    "Kidou Senshi Gundam Thunderbolt: December Sky",
    "Kidou Senshi Gundam Thunderbolt",
    "Sakamoto Days Part 2",
    "Dead Dead Demons Dededede Destruction (ONA)",
    "Kizumonogatari: Koyomi Vamp",
    "Douluo Dalu",
    "Zhu Xian 2nd Season",
    "5-toubun no Hanayome∽",
    "Jibaku Shounen Hanako-kun 2",
    "Hanma Baki: Son of Ogre 2nd Season",
    "Kono Oto Tomare!",
    "Tennis no Oujisama: Zenkoku Taikai-hen - Final",
    "Noragami",
    "Kindaichi Shounen no Jikenbo",
    "Fate/Grand Order: Zettai Majuu Sensen Babylonia",
    "Eyeshield 21",
    "Ling Long 2nd Season",
    "One Piece: Gyojin Tou-hen",
    "Rock wa Lady no Tashinami deshite",
    "Fanren Xiu Xian Chuan: Xinghai Feichi Prologue",
    "Berserk: Ougon Jidai-hen - Memorial Edition",
    "Hidamari Sketch x ☆☆☆",
    "Code Geass: Fukkatsu no Lelouch",
    "Log Horizon",
    "Kaleido Star",
    "Yuru Yuri San☆Hai!",
    "Ie Naki Ko Remy",
    "Karigurashi no Arrietty",
    "Meitantei Conan OVA 09: 10-nengo no Stranger",
    "Date A Live II: Kurumi Star Festival",
    "Meitantei Conan Movie 27: 100-man Dollar no Michishirube",
    "Mahoutsukai no Yome Season 2 Part 2",
    "Atarashii Joushi wa Do Tennen",
    "IDOLiSH7 Movie: LIVE 4bit - BEYOND THE PERiOD",
    "Love Live! The School Idol Movie",
    "One Piece Film: Strong World Episode 0",
    "Kimi to Boku. 2",
    "Hanamonogatari",
    "Overlord III",
    "Bungou Stray Dogs: Dead Apple",
    "Phantom: Requiem for the Phantom",
    "Plastic Memories",
    "Tate no Yuusha no Nariagari",
    "Les Misérables: Shoujo Cosette",
    "Kobayashi-san Chi no Maid Dragon",
    "Tamako Love Story",
    "Love Live! Superstar!!",
    "Summer Ghost",
    "Kokoro Connect: Michi Random",
    "Bishoujo Senshi Sailor Moon S",
    "Full Metal Panic! The Second Raid",
    "Initial D Third Stage",
    "Cike Wu Liuqi",
    "Yakitate!! Japan",
    "Dramaturgy",
    "Ginga Sengoku Gunyuuden Rai",
    "Macross F",
    "Ushio to Tora (TV) 2nd Season",
    "BanG Dream! Film Live 2nd Stage",
    "Aria the Avvenire",
    "Osomatsu-san Movie",
    "Macross: Ougon Jidai-hen - Memorial Edition",
    "Meitantei Conan Movie 02: 14-banme no Target",
    "Doraemon (1979)",
    "Paradise Kiss",
    "Sakigake!! Cromartie Koukou",
    "School Rumble",
    "Kingdom",
    "Drifters",
    "Yuanshen: Weixing Zhi Lu",
    "Yuzuki-san Chi no Yonkyoudai.",
    "Hololive Alternative",
    "Kidou Senshi Gundam: Suisei no Majo - Prologue",
    "New Initial D Movie: Legend 3 - Mugen",
    "Carnival Phantasm",
    "Free! Eternal Summer: Kindan no All Hard!",
    "Berserk: Ougon Jidai-hen II - Doldrey Kouryaku",
    "Non Non Biyori Repeat: Hotaru ga Tanoshinda",
    "K-On!",
    "BanG Dream! Movie: Poppin' Dream!",
    "Megalo Box",
    "Ookiku Furikabutte",
    "Shijou Saikyou no Deshi Kenichi OVA",
    "Jigoku Shoujo Futakomori",
    "Saiunkoku Monogatari",
    "Higurashi no Naku Koro ni",
    "Ookami to Koushinryou II: Ookami to Kohakuiro no Yuuutsu",
    "Mahou Shoujo Lyrical Nanoha: The Movie 1st",
    "Hibike! Euphonium Movie 2: Todoketai Melody",
    "Kami nomi zo Shiru Sekai II",
    "Lupin the IIIrd: Chikemuri no Ishikawa Goemon",
    "Heartcatch Precure!",
    "Zan Sayonara Zetsubou Sensei",
    "Wu Shan Wu Xing (2020)",
    "Wanmei Shijie",
    "Oniisama e...",
    "Meitantei Conan Movie 01: Tokei Jikake no Matenrou",
    "Tennis no Oujisama: Zenkoku Taikai-hen - Semifinal",
    "Love Me: Kaede to Suzu The Animation",
    "Anne Shirley",
    "Meitantei Conan Movie 22: Zero no Shikkounin",
    "High☆Speed! Movie: Free! Starting Days",
    "K-On!!: Keikaku!",
    "Lupin III vs. Meitantei Conan: The Movie",
    "Master Piece The Animation",
    "Clevatess: Majuu no Ou to Akago to Shikabane no Yuusha",
    "Urusei Yatsura (2022) 2nd Season",
    "Dark Gathering",
    "Hug tto! Precure",
    "Noragami Aragoto OVA",
    "Seitokai Yakuindomo* OVA",
    "Carole & Tuesday",
    "Sayonara Zetsubou Sensei",
    "Sekaiichi Hatsukoi OVA",
    "Hoozuki no Reitetsu OVA",
    "Yuru Yuri Nachuyachumi!",
    "Tonikaku Kawaii",
    "Ojamajo Doremi Na-i-sho",
    "Sonny Boy",
    "Kidou Senshi Gundam: Suisei no Majo",
    "Boku no Hero Academia 4th Season",
    "Kuroko no Basket Movie 3: Winter Cup - Tobira no Mukou",
    "Durarara!! Specials",
    "Fumetsu no Anata e Season 3",
    "Musekinin Kanchou Tylor",
    "Mairimashita! Iruma-kun 3rd Season",
    "Michiko to Hatchin",
    "Seihou Bukyou Outlaw Star",
    "Tokyo Revengers",
    "Tiger & Bunny",
    "Shingeki no Kyojin: Chronicle",
    "Kengan Ashura Season 2 Part 2",
    "Hatsukoi Jikan",
    "Oomuro-ke: Dear Sisters",
    "Tokyo Revengers: Tenjiku-hen",
    "Let You Down",
    "Bishoujo Senshi Sailor Moon Cosmos Movie",
    "Seitokai Yakuindomo Movie",
    "Enen no Shouboutai: Ni no Shou",
    "New Initial D Movie: Legend 2 - Tousou",
    "Akachan to Boku",
    "Meitantei Conan Movie 08: Ginyoku no Time Travel Recap",
    "Aoki Hagane no Arpeggio: Ars Nova Movie 2 - Cadenza",
    "Eikoku Koi Monogatari Emma: Molders-hen",
    "Planetarian: Hoshi no Hito",
    "Shanhe Jian Xin",
    "Tanaka-kun wa Itsumo Kedaruge",
    "Sekaiichi Hatsukoi 2",
    "Seto no Hanayome OVA",
    "Little Witch Academia (TV)",
    "Dance Dance Danseur",
    "Flanders no Inu (Movie)",
    "Yuukoku no Moriarty OVA",
    "Giant Robo the Animation: Chikyuu ga Seishi Suru Hi",
    "InuYasha Movie 3: Tenka Hadou no Ken",
    "5-toubun no Hanayome Movie",
    "Tasogare Otome x Amnesia",
    "Crayon Shin-chan",
    "Gungrave",
    "One Piece Film: Red",
    "Danshi Koukousei no Nichijou Specials",
    "Komi-san wa, Comyushou desu.",
    "Jungle wa Itsumo Hare nochi Guu",
    "City Hunter 3",
    "Hidamari Sketch x ☆☆☆ Specials",
    "Slayers Try",
    "Arknights: Rise from Ember",
    "Mashle: Shinkakusha Kouho Senbatsu Shiken-hen",
    "Nige Jouzu no Wakagimi",
    "Mahoujin Guruguru (2017)",
    "Nodame Cantabile: Finale - Mine to Kiyora no Saikai",
    "Tamayura: Sotsugyou Shashin Part 3 - Akogare",
    "Magi: Sinbad no Bouken",
    "Gochuumon wa Usagi desu ka?? Dear My Sister",
    "Jormungand",
    "Beastars",
    "Last Exile",
    "Dragon Ball Kai",
    "Meitantei Conan Movie 09: Suihei Senjou no Strategy",
    "Meitantei Conan Movie 07: Meikyuu no Crossroad",
    "Yuanshen Tiwate Pian",
    "Chainsaw Man Recap",
    "Shinkiro",
    "Emiya-san Chi no Kyou no Gohan",
    "Shin Kidou Senki Gundam Wing: Endless Waltz Tokubetsu-hen",
    "Clannad: After Story - Mou Hitotsu no Sekai, Kyou-hen",
    "Hadashi no Gen",
    "Hibike! Euphonium Movie 3: Chikai no Finale",
    "Igano Kabamaru",
    "Bishoujo Senshi Sailor Moon Crystal Season III",
    "Hanasaku Iroha",
    "Kidou Senshi Zeta Gundam",
    "Kuuchuu Buranko",
    "Space☆Dandy",
    "Zoku Sayonara Zetsubou Sensei",
    "Shingeki no Kyojin OVA",
    "Ie Naki Ko",
    "Promare",
    "Ore Monogatari!!",
    "Final Fantasy VII: Advent Children Complete",
    "Shirokuma Cafe",
    "Zetsuen no Tempest",
    "Shen Yin Wangzuo Movie: Yi Lai Ke Si Chuanqi",
    "Wu Dong Qian Kun 4th Season",
    "Love Live! Superstar!! 3rd Season",
    "Code Geass: Hangyaku no Lelouch I - Koudou",
    "Jormungand: Perfect Order",
    "Yagate Kimi ni Naru",
    "Golden Kamuy",
    "Doupo Cangqiong 3rd Season",
    "Hoozuki no Reitetsu 2nd Season",
    "Kuroko no Basket Movie 1: Winter Cup - Kage to Hikari",
    "Love Live! School Idol Project 2nd Season",
    "Inu-Ou",
    "Break Blade Movie 3: Kyoujin no Ato",
    "Lucky☆Star",
    "Tianbao Fuyao Lu 2nd Season",
    "Inazuma Eleven",
    "Akagami no Shirayuki-hime",
    "Saint Seiya",
    "Cardcaptor Sakura: Clear Card-hen Prologue",
    "Free! Movie 4: The Final Stroke - Zenpen",
    "Gakuen Babysitters Special",
    "Bishoujo Senshi Sailor Moon Eternal Movie 2",
    "Kara no Kyoukai Movie 2: Satsujin Kousatsu (Zen)",
    "Fanren Xiu Xian Chuan",
    "Aria the Crepuscolo",
    "Inochi no Tabekata",
    "Ame wo Matsu,",
    "Zan Sayonara Zetsubou Sensei Bangaichi",
    "Lupin III vs. Meitantei Conan",
    "Tentai Senshi Sunred",
    "Gakkou no Kaidan",
    "The Everlasting Guilty Crown",
    "Overlord Movie 3: Sei Oukoku-hen",
    "Isekai Ojisan",
];

// Simple delay
const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

async function run() {
    console.log("Resolving IDs for Batch 4...");

    // Create a Set for faster lookup
    const foundSet = new Set(FOUND_TITLES);
    let resolved = [];

    const START_PAGE = 31;
    const END_PAGE = 50;

    for (let page = START_PAGE; page <= END_PAGE; page++) {
        console.log(`Scanning page ${page}...`);
        try {
            const res = await getTopAnime(page);
            const animes = res.data || [];

            for (const anime of animes) {
                if (foundSet.has(anime.title)) {
                    resolved.push(`${anime.mal_id}, // ${anime.title}`);
                }
            }

            // Delay to be nice
            await delay(1000);

        } catch (e) {
            console.error("Error in loop:", e);
        }
    }

    const outputContent = resolved.join('\\n    ');
    console.log("------------------------------------------------");
    console.log(`Resolved ${resolved.length} titles. Writing to batch4_confirmed.txt...`);
    fs.writeFileSync('batch4_confirmed.txt', outputContent, 'utf8');
    console.log("Done.");
    console.log("------------------------------------------------");
}

run();
