
export const KEYWORD_TO_TAG = {
    // Power / Fantasy
    'surpuissant': 'Super Power',
    'overpowered': 'Super Power',
    'op': 'Super Power',
    'fort': 'Super Power',
    'magie': 'Magic',
    'magic': 'Magic',
    'sorcier': 'Magic',
    'dragon': 'Dragons',
    'monstre': 'Monster',
    'monster': 'Monster',
    'demon': 'Demon',
    'démon': 'Demon',
    'hero': 'Super Power',
    'héros': 'Super Power',
    'vilain': 'Villainess',
    'anti-hero': 'Anti-Hero',
    'anti-héros': 'Anti-Hero',

    // Setting
    'donjon': 'Dungeon',
    'dungeon': 'Dungeon',
    'tour': 'Tower',
    'tower': 'Tower',
    'école': 'School',
    'school': 'School',
    'lycée': 'School',
    'espace': 'Space',
    'space': 'Space',
    'cyberpunk': 'Cyberpunk',
    'steampunk': 'Steampunk',
    'post-apocalyptique': 'Post-Apocalyptic',
    'apocalypse': 'Post-Apocalyptic',
    'isekai': 'Isekai',
    'autre monde': 'Isekai',
    'monde parallèle': 'Isekai',
    'fantasy': 'Fantasy',

    // Themes
    'vampire': 'Vampire',
    'zombie': 'Zombie',
    'fantôme': 'Ghost',
    'ghost': 'Ghost',
    'ninja': 'Ninja',
    'samourai': 'Samurai',
    'samurai': 'Samurai',
    'pirate': 'Pirates',
    'robot': 'Mecha',
    'mecha': 'Mecha',
    'sport': 'Sports',
    'musique': 'Music',
    'idol': 'Idols',
    'cuisine': 'Food',
    'food': 'Food',
    'jeu': 'Game',
    'game': 'Game',
    'survie': 'Survival',
    'survival': 'Survival',
    'horreur': 'Horror',
    'peur': 'Horror',
    'romance': 'Romance',
    'amour': 'Romance',
    'drame': 'Drama',
    'comedie': 'Comedy',
    'drole': 'Comedy',
    'marrant': 'Comedy',
    'tranche de vie': 'Slice of Life',
    'quotidien': 'Slice of Life',
    'voyage': 'Adventure',
    'aventure': 'Adventure',
    'action': 'Action',
    'combat': 'Badass',
    'bagarre': 'Action',

    // Demographics/Tropes
    'harem': 'Harem',
    'reverse harem': 'Reverse Harem',
    'bl': 'Boys Love',
    'shonen ai': 'Boys Love',
    'shounen ai': 'Boys Love',
    'yaoi': 'Boys Love',
    'gl': 'Yuri',
    'shoujo ai': 'Yuri',
    'yuri': 'Yuri',
    'vengeance': 'Revenge',
    'revenge': 'Revenge',
    'romantique': 'Romance',
    'triste': 'Tragedy'
};
